version: '3.9'

services:
  face_swap_service:
    build: .
    container_name: face_swap_container
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - "9222:9222"